const mongoose = require('mongoose');

var sampark = new mongoose.Schema({
    'First Name': String,
    'Middle Name': String,
    'Last Name': String,
    Patrika: String,
    'Verified Date': String,
    'Profile Meter': Number,
    'Flat No': String,
    'Building Name': String,
    'Street Name': String,
    Relationship: String,
    'Education Status': String,
    'Education Others': String,
    'Major Subject': String,
    Verified: String,
    'Family Id': String,
    'Key Member': String,
    'Mobile 2': String,
    'Last Sabha Attended': String,
    'Aym 2015': String,
    'Full Name': String,
    'Attending Sabha': String,
    'Leaving Date': String,
    'Yogibaal Exp': String,
    'Member Id': String,
    'Ambrish Code': String,
    'NickName': String,
    'Yogibaal': String,
    'YDSMUM': String,
    'Patrika Exp': String,
    'Suburb': String,
    'Birth Date': String,
    'Mobile': String,
    'Ref Name': String,
    'FollowUp Name': String,
    'Gender': String,
    'Email': String,
    'Sabha': String,
    'Present': String,
    'Secondary Email': String,
    'Address': String,
    'Landmark': String,
    'Area': String,
    'PinCode': String,
    'Home Phone': String,
    'Office Phone': String,
    'Doing Puja': String,
    'Education': String,
    'Company Name': String,
    'Occupation': String,
    'Designation': String,
    'Marital Status': String,
    'Blood Group': String,
    'In Groups': String,
    'Aniversary': String,
    'Joining Date': String,
    'Latitute': String,
    'Longitude': String,
    'My References': String,
    'My Followups': String,
    'Mandal Name': String,
    'Last Attended': String,
    '% Present': Number,
    'Sabha Status': String
}, { timestamps: true });

sampark.index({ 'Mobile': 1, 'Full Name': 1 })

module.exports = mongoose.model("sampark", sampark);
